#include "injector.h"

#include "injector.h"

Injector::Injector()
    : unit_type("injector"),
    name("injector"),
    type(Droplet),
    injection_type(single),
    local_reference_frame("global"),
    numpts(10),
    dpm_fname("\" \""),
    surfaces({-1}),
    boundary({-1}),
    stochastic(false),
    random_eddy(false),
    ntries(1),
    time_scale_constant(0.15),
    cloud(false),
    cloud_min_dia(0),
    cloud_max_dia(100000),
    material(""),
    scale_by_area(false),
    use_face_normal(false),
    random_surface(false),
    devolatilizing_species(""),
    evaporating_species(""),
    oxidizing_species(""),
    product_species(""),
    rr_disturb(true),
    rr_uniform_ln_d(false),
    evaporating_liquid(false),
    evaporating_material(""),
    liquid_fraction(-1),
    dpm_domain("none"),
    collision_partner("dem-unknow"),
    parcel_number(500),
    parcel_mass(1e-9),
    parcel_diameter(1e-5),
    parcel_model(standard),
    drag_law(spherical),
    shape_factor(1),
    cunningham_correction(1),
    drag_fcn("none"),
    brownian_motion(false),
    seco_breakup_on(false),
    seco_breakup_tab(false),
    seco_breakup_wave(false),
    seco_break_up_khrt(false),
    seco_breakup_ssd(false),
    seco_breakup_madahushi(false),
    seco_breakup_schmehl(false),
    seco_breakup_tab_y0(0),
    number_tab_diameters(0),
    seco_breakup_wave_b1(0),
    seco_breakup_wave_b0(0),
    seco_breakup_khrt_cl(0),
    seco_breakup_khrt_ctau(0),
    seco_breakup_khrt_crt(0),
    seco_breakup_ssd_we_cr(0),
    seco_breakup_ssd_core_bu(0),
    seco_breakup_ssd_np_target(0),
    seco_breakup_ssd_x_si(0),
    seco_breakup_madabushi_c0(0),
    seco_breakup_madabushi_column_drag_cd(0),
    seco_breakup_madabushi_ligament_factor(0),
    seco_breakup_madabushi_jet_diameter(0),
    seco_breakup_schmehl_np(0),
    //swit("\"Default\""),
    //udf_inject_init("\"none\""),
    //udf_heat_mass("none"),
    volume_specification(zone),
    volume_streams_spec(total_parcel_count),
    volume_streams_total(0),
    volume_bgeom_shapes(sphere),
    volume_bgeom_min(0, 0, 0),
    volume_bgeom_max(0, 0, 0),
    volume_bgeom_radius(0),
    volume_bgeom_viconeangle(0),
    mass_input_on(false),
    volfrac_input_on(false),
    rotation_on(false),
    rot_drag_law(none),
    rot_lift_law(none_),
    cone_type(point),
    uniform_mass_dist_on(false),
    spatial_staggering_std_inj_on(false),
    spatial_staggering_atomizer_on(true),
    stagger_radius(0),
    rough_wall_on(false),
    cphace_domain("none"),
    pos(0, 0, 0),
    pos2(0, 0, 0),
    ff_center(0, 0, 0),
    ff_virtual_origin(0, 0, 0),
    ff_normal(0, 0, 0),
    vel(0, 0, 0),
    vel2(0, 0, 0),
    ang_vel(0, 0, 0),
    ang_vel2(0, 0, 0),
    atomizer_axis(0, 0, 0),
    diameter(0),
    diameter2(0),
    temperature(0),
    temperature2(0),
    flow_rate(0),
    flow_rate2(0),
    unsteady_start(0),
    unsteady_stop(0),
    start_at_flow_time_in_unsteady_inj_file(0),
    interval_to_repeat_in_unsteady_inj_file(0),
    unsteady_ca_start(0),
    unsteady_ca_stop(0),
    vapor_pressure(0),
    inner_diameter(0),
    outer_diameter(0),
    half_angle(0),
    plain_length(0),
    plain_corner_size(0),
    plain_const_a(0),
    pswirl_inj_press(0),
    airbl_rel_vel(0),
    effer_quality(0),
    effer_t_sat(0),
    ff_oriface_width(0),
    phi_start(0),
    phi_stop(0),
    sheet_const(0),
    lig_const(0),
    effer_const(0),
    effer_half_angle_max(0),
    ff_sheet_const(0),
    atomizer_disp_angle(0),
    axis(0, 0, 0),
    vel_mag(0),
    ang_vel_mag(0),
    cone_angle(0),
    inner_radius(0),
    radius(0),
    swirl_frac(0),
    total_flow_rate(0),
    total_mass(0),
    rr_min(0),
    rr_max(0),
    rr_mean(0),
    rr_numdia(0),
    posr(0, 0, 0),
    posu(0, 0, 0)
{

}

Injector::~Injector()
{

}



